version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${NODE_DOCKER_PORT}:${NODE_LOCAL_PORT}
    stdin_open: true
    tty: true
  #specivy what folder in host comp will be create
volumes:
  db: